### Get all messages
GET http://localhost:8080/messages

### Create a new message
POST http://localhost:8080/messages
Content-Type: application/json

{
  "content":"hey after DI"
}

### Get a particular message using id
GET http://localhost:8080/messages/528
